### ISSUE TITLE
Frosit\Utils\Mysql\mysqli_stmt, instance of mysqli_stmt given

### ISSUE THREAD

**Issue by dudzio12** [frosit/magerun-rewritetoolset#3]
When using any of this extension method:
`PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Frosit\Utils\Mysql\MysqliDb::_dynamicBindResults() must be an instance of Frosit\Utils\Mysql\mysqli_stmt, instance of mysqli_stmt given, called in (...)/.modman/magerun-rewritetoolset/src/Frosit/Utils/Mysql/MysqliDb.php on line 451 and defined in (...)/.modman/magerun-rewritetoolset/src/Frosit/Utils/Mysql/MysqliDb.php:1450`

**Comment by juliyvchirkov** [comment]
@dudzio12 please review https://github.com/frosit/magerun-rewritetoolset/pull/4 to patch your local source

**Comment by frosit** [comment]
Fixed in #4 thanks!
